### ISSUE TITLE
Wait for and test on localhost?

### ISSUE THREAD

**Issue by rayshan** [anthonyvscode/newman-action#27]
Thanks for this GitHub Action! Would you consider this use case?

1. Run CLI command to start server at localhost:port (my server is written in Node)
2. Wait for port to be available
3. Run newman against localhost:port

**Comment by patrickwyler** [comment]
Wouldn't add this to this action, better add a step like the following one:

     - name: Wait until app is started up
        run: while [[ "$(curl -k -m100 -s -o /dev/null -w ''%{http_code}'' https://localhost:8080/)" != "200" ]]; do sleep 5 && echo wait; done

**Comment by rayshan** [comment]
Makes sense, thanks!
